buildscript {
    repositories { google(); mavenCentral() }
    dependencies { classpath 'com.android.tools.build:gradle:7.3.0' }
}
apply plugin: 'com.android.application'
android { compileSdkVersion 33; namespace "test.test" }
repositories { mavenCentral(); google(); maven { url 'https://jitpack.io' } }
dependencies { implementation 'com.klinker24:android-smsmms:7.1.0' }
