// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNHZKJ9awtPkqgwQ5mHwSvc8SkA7E8fUM',
    appId: '1:255796319813:web:5d3efdf8ea370bc4fab52c',
    messagingSenderId: '255796319813',
    projectId: 'xyzd-7254d',
    authDomain: 'xyzd-7254d.firebaseapp.com',
    storageBucket: 'xyzd-7254d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlosXNA8SToNkFTy0ORYm8YhP6hcSzsuE',
    appId: '1:255796319813:android:f8cc273d69ea1b00fab52c',
    messagingSenderId: '255796319813',
    projectId: 'xyzd-7254d',
    storageBucket: 'xyzd-7254d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqan8bwnSzTNnovhIDQGV6t_tmsKp2JJQ',
    appId: '1:255796319813:ios:0dedf06004f71ed5fab52c',
    messagingSenderId: '255796319813',
    projectId: 'xyzd-7254d',
    storageBucket: 'xyzd-7254d.firebasestorage.app',
    iosBundleId: 'com.example.adminBroker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqan8bwnSzTNnovhIDQGV6t_tmsKp2JJQ',
    appId: '1:255796319813:ios:0dedf06004f71ed5fab52c',
    messagingSenderId: '255796319813',
    projectId: 'xyzd-7254d',
    storageBucket: 'xyzd-7254d.firebasestorage.app',
    iosBundleId: 'com.example.adminBroker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNHZKJ9awtPkqgwQ5mHwSvc8SkA7E8fUM',
    appId: '1:255796319813:web:98be130e6d4965dbfab52c',
    messagingSenderId: '255796319813',
    projectId: 'xyzd-7254d',
    authDomain: 'xyzd-7254d.firebaseapp.com',
    storageBucket: 'xyzd-7254d.firebasestorage.app',
  );
}
