// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA72tSwlX3t6AWKSQ6nrHPKNDvPEpp2yHU',
    appId: '1:368388519683:web:9de3713393f7e7fd9b9b36',
    messagingSenderId: '368388519683',
    projectId: 'replymate-1f925',
    authDomain: 'replymate-1f925.firebaseapp.com',
    databaseURL: 'https://replymate-1f925-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'replymate-1f925.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8IP0ZF9qJ9GOQbw5BPO2D8wXuD8rLPPY',
    appId: '1:368388519683:android:583f207a154aa7309b9b36',
    messagingSenderId: '368388519683',
    projectId: 'replymate-1f925',
    databaseURL: 'https://replymate-1f925-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'replymate-1f925.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd6nZBK17lLYd6ltkcj8u0EjsshTdJYqQ',
    appId: '1:368388519683:ios:a4094713d5fdadd49b9b36',
    messagingSenderId: '368388519683',
    projectId: 'replymate-1f925',
    databaseURL: 'https://replymate-1f925-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'replymate-1f925.firebasestorage.app',
    androidClientId: '368388519683-5c2s66ptl1jecgprjdnpt1p2lu3te1hu.apps.googleusercontent.com',
    iosClientId: '368388519683-1i3bkrrj8al3ffp8bpi0l6hol3u3bmhk.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminBroker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd6nZBK17lLYd6ltkcj8u0EjsshTdJYqQ',
    appId: '1:368388519683:ios:a4094713d5fdadd49b9b36',
    messagingSenderId: '368388519683',
    projectId: 'replymate-1f925',
    databaseURL: 'https://replymate-1f925-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'replymate-1f925.firebasestorage.app',
    androidClientId: '368388519683-5c2s66ptl1jecgprjdnpt1p2lu3te1hu.apps.googleusercontent.com',
    iosClientId: '368388519683-1i3bkrrj8al3ffp8bpi0l6hol3u3bmhk.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminBroker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA72tSwlX3t6AWKSQ6nrHPKNDvPEpp2yHU',
    appId: '1:368388519683:web:cb3ba64b499bbe449b9b36',
    messagingSenderId: '368388519683',
    projectId: 'replymate-1f925',
    authDomain: 'replymate-1f925.firebaseapp.com',
    databaseURL: 'https://replymate-1f925-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'replymate-1f925.firebasestorage.app',
  );
}
